account/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.login, name='login'),
    # url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile')
]

tracker/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'tracker'

urlpatterns = [
	# /
    path('', views.LandingView.landing, name ="landing"),

    # /dashboard
    path('dashboard', login_required(views.Dashboard.index), name="dashboard"),

    # /tracker
    path('tracker', login_required(views.IndexView.as_view()), name ="expense"),

    # /add
    path('tracker/add', login_required(views.ExpenseCreate.as_view()), name="create_expense"),

    # /update/{id}
    path('tracker/update/<int:pk>', login_required(views.ExpenseUpdate.as_view()), name="update_expense"),

    # /delete/{id}
    path('tracker/delete/<int:pk>', login_required(views.ExpenseDelete.as_view()), name="delete_expense"),

    # /export
    path('tracker/export', login_required(views.ReportView.export), name="export"),

    # /analytics
    # FIXME: redirect to dashboard
    path('analytics', login_required(views.Dashboard.index), name="analytics"),

    # /analytics/2018
    path('analytics/<int:year>', login_required(views.AnalyticsView.annually), name="annually"),

    # /analytics/2018/02
    path('analytics/<int:year>/<int:month>', login_required(views.AnalyticsView.monthly), name="monthly"),

    # /analytics/2018/02/20
    path('analytics/<int:year>/<int:month>/<int:day>', login_required(views.AnalyticsView.daily), name="daily"),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tracker.urls')),
    path('', include('accounts.urls'))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

tracker/models.py
from django.db import models
from django.urls import reverse


class Expense(models.Model):
    date = models.DateField()
    description = models.CharField(max_length=1000, null=True)
    type = models.CharField(max_length=30)
    payment = models.CharField(max_length=30)
    amount = models.FloatField()
    created_by = models.CharField(max_length=100)
    created_at = models.DateField()

    class Meta:
        verbose_name = 'Expense'
        verbose_name_plural = 'Expenses'
        ordering = ['-id']

    def get_absolute_url(self):
        return reverse('tracker:expense')

tracker/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, ButtonHolder, Submit
from django.forms import ModelForm
from .models import Expense

class ExpenseTableHelper(FormHelper):
    date = forms.DateField(
        widget=forms.TextInput(
            attrs={'type': 'date'}
        )
    )
    form_method = 'GET'
    layout = Layout(
        Field('date', placeholder='YYYY-MM-DD'),
        Field('description'),
        Field('type'),
        Field('payment'),
        Field('amount'),
        Submit('submit', 'Filter'),
    )


class DateInput(forms.DateInput):
    input_type = 'date'


class AddExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = [
            'date',
            'description',
            'type',
            'payment',
            'amount'
        ]
        widgets = {
            'date': DateInput(),
        }

tracker/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django_tables2 import RequestConfig
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db.models import Sum, Count
from .tables import ExpenseTable
from .models import Expense
from .forms import ExpenseTableHelper
from .filters import ExpenseFilter
from .utils import AmountUnitUtil
from django.http import HttpResponse
from calendar import monthrange
from .forms import AddExpenseForm
import csv
import random
import datetime


class Dashboard():
    template_name = "tracker/dashboard.html"

    def index(request):
        # init
        avg_year = 0
        avg_month = 0
        avg_day = 0

        now = datetime.datetime.now()

        # get user expense objects
        exp = Expense.objects.filter(created_by=request.user)

        # count total record
        total_records = exp.count()

        # count total record in this month
        current_month = now.month
        total_records_in_this_month = exp.filter(created_at__month=current_month).count()
        if total_records_in_this_month is None:
            total_records_in_this_month = 0

        # count total record in last month
        last_month = now.month - 1
        if last_month<0:
            last_month = 11
        total_records_in_last_month = exp.filter(created_at__month=last_month).count()
        if total_records_in_last_month is None:
            total_records_in_last_month = 0

        print(total_records_in_this_month)
        print(total_records_in_last_month)
        # diff between this month and last month
        if total_records == 0:
            total_records_diff = 0
        else:
            total_records_diff = ( (total_records_in_this_month - total_records_in_last_month) / total_records ) * 100

        # sum up all the expenses
        total_expenses = exp.aggregate(amount=Sum('amount'))['amount']
        if total_expenses is None:
            total_expenses = 0

        # sum up all the expenses in this month
        total_expenses_in_this_month = exp.filter(created_at__month=current_month).aggregate(amount=Sum('amount'))['amount']
        if total_expenses_in_this_month is None:
            total_expenses_in_this_month = 0

        # sum up all the expenses in last month
        total_expenses_in_last_month = exp.filter(created_at__month=last_month).aggregate(amount=Sum('amount'))['amount']
        if total_expenses_in_last_month is None:
            total_expenses_in_last_month = 0

        # diff between this month and last month
        if total_expenses == 0:
            total_expenses_diff = 0
        else:
            total_expenses_diff = ( (total_expenses_in_this_month - total_expenses_in_last_month) / total_expenses ) * 100

        # get all categories
        categories = list(exp.values('type').distinct().order_by('type').values_list('type', flat=True))

        # get categories record count
        categories_record_cnt = list(exp.values('type').annotate(the_count=Count('type')).order_by('type').values_list('the_count', flat=True))

        # categories count
        categories_cnt = exp.values('type').annotate(the_count=Count('type')).count()
        if categories_cnt is None:
            categories_cnt = 0

        # total expense per category
        categories_expense = list(exp.values('type').order_by('type').annotate(the_count=Sum('amount')).values_list('the_count', flat=True))

        categories_color_arr = []
        for cat in categories:
            # generate random color
            r = lambda: random.randint(0, 255)
            color = '#%02X%02X%02X' % (r(), r(), r())
            categories_color_arr.append(color)

        # categories count in this month
        categories_in_this_month = exp.filter(created_at__month=current_month).values('type').annotate(the_count=Count('type')).count()
        if categories_in_this_month is None:
            categories_in_this_month = 0

        # categories count in last month
        categories_in_last_month = exp.filter(created_at__month=last_month).values('type').annotate(the_count=Count('type')).count()
        if categories_in_last_month is None:
            categories_in_last_month = 0

        # diff between this month and last month
        if categories_cnt == 0:
            total_categories_diff = 0
        else:
            total_categories_diff = ((categories_in_this_month - categories_in_last_month) / categories_cnt) * 100

        # list out dates for the following processing.
        dates = list(exp.values('date')
                     .values_list('date', flat=True))

        # avg amount per year, per month and per day
        year_arr = []
        month_arr = []
        day_arr = []

        for date in dates:
            if date.year not in year_arr:
                year_arr.append(date.year)
            if date.year not in month_arr:
                month_arr.append(date.month)
            if date.year not in day_arr:
                day_arr.append(date.day)

        if total_expenses > 0:
            avg_year = AmountUnitUtil.convertToMills(total_expenses / year_arr.__len__())
            avg_month = AmountUnitUtil.convertToMills(total_expenses / month_arr.__len__())
            avg_day = AmountUnitUtil.convertToMills(total_expenses / day_arr.__len__())
            total_expenses = AmountUnitUtil.convertToMills(total_expenses)

        # Get Latest 30 days records

        latest30DaysArr = list(exp.filter(created_at__lte=datetime.datetime.today(),
                                       created_at__gt=datetime.datetime.today() - datetime.timedelta(days=30))
                            .values('date').distinct().order_by('date').values_list('date', flat=True))

        latest30DaysLabel = []
        for day in latest30DaysArr:
            latest30DaysLabel.append(day.strftime('%d/%m'))


        latest30DaysData = list(exp.filter(created_at__lte=datetime.datetime.today(), created_at__gt=datetime.datetime.today()-datetime.timedelta(days=30))
                             .values('date').distinct().order_by('date')
                             .annotate(amount=Sum('amount')).values_list('amount', flat=True))

        context = {
            'context_type': 'dashboard',
            'total_records': total_records,
            'total_expenses': total_expenses,
            'categories': categories,
            'categories_record_cnt': categories_record_cnt,
            'categories_cnt': categories_cnt,
            'categories_expense': categories_expense,
            'categories_color_arr': categories_color_arr,
            'avg_year': avg_year,
            'avg_month': avg_month,
            'avg_day':avg_day,
            'current_year': now.year,
            'current_month': now.month,
            'current_day': now.day,
            'latest30DaysLabel': latest30DaysLabel,
            'latest30DaysData': latest30DaysData,
            'totalRecordsInThisMonth': total_records_in_this_month,
            'totalRecordsInLastMonth': total_records_in_last_month,
            'totalExpensesInThisMonth': float("{0:.2f}".format(total_expenses_in_this_month)),
            'totalExpensesInLastMonth': float("{0:.2f}".format(total_expenses_in_last_month)),
            'categories_in_this_month': categories_in_this_month,
            'categories_in_last_month': categories_in_last_month,
            'total_expenses_diff': float("{0:.2f}".format(total_expenses_diff)),
            'total_records_diff': float("{0:.2f}".format(total_records_diff)),
            'total_categories_diff': float("{0:.2f}".format(total_categories_diff))

        }

        return render(request, "tracker/dashboard.html", context)


class IndexView(generic.ListView):
    template_name = "tracker/index.html"
    context_object_name = "records"
    model = Expense
    table_class = ExpenseTable
    filter_class = ExpenseFilter
    formhelper_class = ExpenseTableHelper

    def get_queryset(self):
        return Expense.objects.filter(created_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        filter = ExpenseFilter(self.request.GET, queryset=self.get_queryset(**kwargs))
        filter.form.helper = ExpenseTableHelper()
        table = ExpenseTable(filter.qs)
        table.order_by = '-date'
        RequestConfig(self.request, paginate={'per_page': 10}).configure(table)
        context['filter'] = filter
        context['table'] = table
        return context


class ExpenseCreate(CreateView):
    model = Expense
    form_class = AddExpenseForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        obj.created_at = datetime.datetime.now()
        obj.save()
        return HttpResponseRedirect(reverse_lazy('tracker:expense'))


class ExpenseUpdate(UpdateView):
    model = Expense
    fields = [
        'date',
        'description',
        'type',
        'payment',
        'amount'
    ]


# obsolete
class ExpenseDelete(DeleteView):
    model = Expense
    success_url = reverse_lazy('tracker:expense')


class AnalyticsView(generic.ListView):
    template_name = "analytics/index.html"
    context_object_name = "records"
    model = Expense

    def annually(request, year):
        # get user expense objects
        exp = Expense.objects.filter(created_by=request.user)

        # retrieve distinct types
        expense_type = list(exp.filter(date__year=year).values('type').distinct().order_by()
                                 .values_list('type', flat=True))

        datasets = []
        months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October",
                  "November", "December"]

        for type in expense_type:
            # expense

tracker/templates/tracker/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Squirrel</title>
    {% load staticfiles %}

    <script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script src="{% static 'main.js' %}"></script>

    <link href="https://fonts.googleapis.com/css?family=Nanum+Pen+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>



    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />

</head>
<body>
<header id="header" class="page-topbar">
 <div class="navbar-fixed">
    <nav class="navbar">
      <div class="nav-wrapper">
        <a class="navbar-brand" href="{% url 'tracker:expense' %}">Squirrel</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
              <li>
                    <a href="{% url 'tracker:dashboard' %}">
                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp; Dashboard
                    </a>
                </li>
                <li>
                    <a href="{% url 'tracker:expense' %}">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Expense Overview
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'tracker:create_expense' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Expense
                    </a>
                </li>
                <li><a href="{% url 'profile'%}">{{ user.get_username }}</a></li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
              {% else %}
                     <li><a href="{% url 'login'%}?next={{request.path}}">Register</a></li>
                     <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
                {% endif %}
          </ul>
      </div>
    </nav>
  </div>
</header>

    {% block body %}
    {% endblock %}

</body>
</html>

tracker/templates/tracker/expense_form.html
{% extends 'tracker/base.html'%}

{% block body %}
<div class="container">
 <div class="row">
      <div class="col s12 m12">
        <div class="card-panel add-expense-form">
          <div class="row">
            <form class="col s12 form-horizontal" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% include 'tracker/form_template.html' %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
          </div>
        </div>
      </div>
</div>
{% endblock %}

tracker/templates/tracker/form_template.html
{% for field in form %}
<div class="row">
    <span class="text-danger small">
         {{ field.errors }}
     </span>
    <div class="input-field col s12">
     {{ field }}
      <label>{{ field.label_tag }}</label>
    </div>
  </div>

{% endfor %}

tracker/templates/tracker/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Expense Tracker</title>
    {% load staticfiles %}
    {% load bootstrap3 %}

    <script src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
    {% bootstrap_javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script src="{% static 'main.js' %}"></script>

    <link href="https://fonts.googleapis.com/css?family=Nanum+Pen+Script" rel="stylesheet">
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}" />

</head>
<body>
    <nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'tracker:expense' %}">Expense Tracker</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'tracker:expense' %}">
                        <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Expense Overview
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'tracker:create_expense' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Expense
                    </a>
                </li>
                <li>
                    <a href="{% url 'tracker:analytics' %}">
                        <span class="glyphicon glyphicon-tasks" aria-hidden="true"></span>&nbsp; Expense Analytics
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

    {% block body %}
    {% endblock %}

</body>
</html>

tracker/templates/tracker/index.html
{% extends 'tracker/base.html'%}
{% load django_tables2 crispy_forms_tags %}

{% block body %}
<div class="container expense-overview">
    <div class="row">
         <div class="col">
            <button type="submit" class="open-filter-btn btn btn-success">
              Filter
            </button>
         </div>
        <div class="col">
            <form method="GET" action="/tracker/export">
                <button type="submit" class="export-btn btn btn-success">Export</button>
            </form>
        </div>

    </div>

    <div class="row">
       <div class="col m12">
           {% render_table table %}
       </div>
    </div>


    <div id="filterPanel" class="filterPanel">
      <a href="javascript:void(0)" class="closebtn">&times;</a>
          <form action="" method="get">
        {% crispy filter.form filter.form.helper %}
        </form>
    </div>

{% endblock %}
</div>